Adds a class to support Netapp driver for External Storage
mesosphere/dcos-commons pull request #3296
Opened 2020-09-08 20:58 UTC by farhan5900

2020-09-08 21:52 UTC, kaiwalyajoshi requested changes

2020-09-08 21:52 UTC, kaiwalyajoshi commented on sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/NetAppVolumeProvider.java
> +        .collect(Collectors.joining(";"));
@farhan5900 these are the options for Portworx Storage Driver, NetApp has different options documented here:
https://netappdvp.readthedocs.io/en/stable/use/index.html#volume-driver-cli-options

Especially ones like `SHARED_KEY` are invalid I'd assume.

2020-09-08 21:53 UTC, kaiwalyajoshi commented
@farhan5900 please address the compile errors associated with your changes.

2020-09-09 23:10 UTC, closed without merging

2020-09-09 23:16 UTC, farhan5900 commented
Moved this to another [PR#3297](https://github.com/mesosphere/dcos-commons/pull/3297).